obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#ifdef VENDOR_EDIT /* lizhijie@BSP.CHG.Basic, 2020/02/25, lzj Add for charging */
obj-$(CONFIG_OPPO_SM7125_CHARGER)	+= oppo/
#endif